name: Python tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"
  HATCH_VERSION: "1.14.2"

jobs:
  test:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
      with:
        python-version: "${{matrix.python-version}}"
        cache: "pip"

    - name: Install Hatch
      uses: pypa/hatch@install
      with:
        version: "${{ env.HATCH_VERSION }}"

    - name: Run type check
      run: hatch run types:check

    - name: Run formatter
      run: hatch fmt

    - name: Run pre-commit
      run: hatch run pre-commit run --all
      env:
        SKIP: nitpick,hatch-fmt,hatch-types

    - name: Run tests
      run: hatch test --python ${{ matrix.python-version }} --cover --randomize --retries 2 --retry-delay 1

    - uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
      with:
        name: "build-${{ matrix.python-version }}"
        fail_ci_if_error: true
        use_oidc: true
